[tool.poetry]
name = "llm-algorithm"
version = "0.1.0"
description = "LLM algorithm research project"
authors = []
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.11.0"
jupyter = "^1.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
